---
- name: Ensure dependencies are installed.
  apt:
    name:
      - curl
      - apt-transport-https
    state: present

- name: Add Jenkins apt repository key.
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present

- name: Add Jenkins apt repository.
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: true

- name: Ensure Jenkins is installed.
  apt:
    name: jenkins
    state: present
  notify: configure default users

  # Update Jenkins and install configured plugins.
- include_tasks: plugins.yml