---
# This installs all OS-level dependencies which are available
- name: Install toolchain
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - cmake
    - libblas-dev
    - liblapack-dev
    - build-essential
    - libboost-all-dev
    - doxygen
